### ISSUE TITLE
Wrong group generator for rfc5054 8192-bit group

### ISSUE THREAD

**Issue by Vayu** [symeapp/srp-client#9]
The g should be 19 decimal, while the code has 0x19
https://github.com/symeapp/srp-client/blob/master/src/srp-client.js#L490

**Comment by louismullie** [comment]
The g is stored in decimal format.

**Comment by Vayu** [comment]
Isn't that loading it as hexadecimal?
https://github.com/symeapp/srp-client/blob/master/src/srp-client.js#L25
```
this.g = new BigInteger(initVal.g, 16);
```

**Comment by louismullie** [comment]
Hmm, yes you are right. This only affects 8192-bit group. Do you want to submit a PR?
